name: CI/CD Pipeline
on: 
  pull_request:
  push:
    branches: 
      - olt

jobs:
  build: 
    name: Build front-end artifact
    needs:
      - audit
    runs-on: ubuntu-latest
    steps:
      - name: Checking out that code
        uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Cache the deps
        uses: actions/cache@v3
        with: 
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json')}}

      - name: Install deps
        run: cd frontend && npm i
      
      - name: Compile code
        run: cd frontend && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend/build
  
  audit: 
    name: Audit the frontend deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Run an audit
        run: cd frontend && npm audit --production
  
  lint: 
    name: Ensure code style
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Cache the deps
        uses: actions/cache@v3
        with: 
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json')}}

      - name: Install deps
        run: cd frontend && npm i
        
      - name: Run the linter
        run: cd frontend && npm run lint
  
  test:
    name: Run the unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Cache the deps
        uses: actions/cache@v3
        with: 
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json')}}
      
      - name: Unit tests
        run: cd frontend && npm run test-ci
  
  static-analysis:
    name: Run Static Code Analysis
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          config-file: ./.github/codeql/codeql.config.yml

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install Deps
        run: cd frontend && npm i

      - name: Build
        run: cd frontend && npm run build

      # - name: Perform Analysis
      #   uses: github/codeql-action/analyze@v2

  deploy:
    name: Deploy Frontend Artifact
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - static-analysis
    if: github.ref == 'refs/heads/olt'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1