name: CI/CD Pipeline
run-name: "🛠️ CI/CD: ${{ github.event.head_commit.message }} (${{ github.sha }})"
on:
  push: 
    branches:
      - blue-green-demo   #normally 'main'

jobs:
  ci-frontend:
    uses: ./.github/workflows/ci-frontend.yml
    with:
      ref: ${{ github.sha }}    

  ci-backend:
    uses: ./.github/workflows/ci-backend.yml
    with:
      ref: ${{ github.sha }}    

  deploy:
    needs: [ci-frontend, ci-backend]
    uses: ./.github/workflows/deploy.yml
    with: 
      ref: ${{ github.sha }}    
    secrets: inherit

  verify:
    needs: [deploy]
    uses: ./.github/workflows/verify.yml
    with: 
      ref: ${{ github.sha }}
      backend_url: ${{ needs.deploy.outputs.backend_url }}
      frontend_url: ${{ needs.deploy.outputs.frontend_url }}
      
  promote:
    needs: [verify]
    uses: ./.github/workflows/promote.yml
    with: 
      ref: ${{ github.sha }}
      s3_bucket_hostname: ${{ needs.deploy.outputs.s3_bucket_hostname }}

  # failure:
  #   needs: [deploy, verify, promote]
  #   if: failure()
  #   uses: ./.github/workflows/cleanup.yml
  #   with: 
  #     ref: ${{ github.sha }}
  #     env_name: Green
  #     reason: failure
  #   secrets: inherit