name: Verify
run-name: "🧪 CD: Verifying Environment (${{ inputs.ref }})"
on:
  workflow_call:
    inputs:
      backend_url:
        required: true
        type: string
      frontend_url:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  frontend:
    name: 🧪 Check Frontend
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Frontend Smoke Test
        run: |
          export TEST_URL=${{ inputs.frontend_url }}
          cd frontend/e2e
          npm install
          npm run smoke

  backend:
    name: 🧪 Check Backend
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Backend Smoke Test
        run: |
          export BACKEND_URL=${{ inputs.backend_url }}
          cd backend/e2e
          chmod +x backend-smoke.sh
          ./backend-smoke.sh

      #- name: Simulate an error
      #  run: exit 1  